# Generated by Django 4.1 on 2023-08-23 21:24

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PredefinedAOI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aoi_name', models.CharField(default='', help_text='AOI Name', max_length=100)),
                ('aoi_country', models.CharField(help_text='AOI Country', max_length=2)),
                ('aoi_geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
