# Generated by Django 4.1 on 2023-08-28 17:36

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scap', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoundaryFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_id', models.IntegerField()),
                ('name_es', models.CharField(max_length=17)),
                ('nomedep', models.CharField(max_length=1)),
                ('nomemun', models.CharField(max_length=1)),
                ('pais', models.CharField(max_length=17)),
                ('fid', models.CharField(max_length=20)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
