# Generated by Django 4.1 on 2024-01-31 18:00

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('scap', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AGBSource',
            fields=[
                ('agb_id',
                 models.CharField(help_text='AGB ID number', max_length=10, primary_key=True, serialize=False)),
                ('agb_name', models.CharField(default='', help_text='AGB Data Source name', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ForestCoverSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fcs_name', models.CharField(default='', help_text='Forest Cover Data Source Name', max_length=100)),
                ('fcs_color',
                 colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=25, samples=None)),
                ('fcs_description', models.TextField(default='', help_text='Forest Cover Data Source Description')),
                (
                    'fcs_metadata',
                    models.URLField(default='https://', help_text='Forest Cover Data Source Metadata URL')),
                ('private', models.BooleanField(default=False, help_text='Private data source?')),
            ],
        ),
        migrations.CreateModel(
            name='Emissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(help_text='Year')),
                ('baseline_year',
                 models.IntegerField(blank=True, help_text='Baseline Year for emissions calculations', null=True)),
                ('lc_agb_value', models.FloatField(help_text='Value')),
                ('agb_id',
                 models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='scap.agbsource',
                                   verbose_name='AGB')),
                ('aoi_id',
                 models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='scap.predefinedaoi',
                                   verbose_name='AOI')),
                ('lc_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT,
                                            to='scap.forestcoversource', verbose_name='LandCover')),
            ],
        ),
    ]
