# Generated by Django 4.1 on 2023-08-28 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scap', '0002_boundaryfiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boundaryfiles',
            name='nomedep',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
