# Generated by Django 4.1 on 2024-02-08 18:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('scap', '0003_alter_emissions_aoi_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='emissions',
            name='total_agb',
            field=models.FloatField(default=0.0, help_text='Total AGB'),
        ),
        migrations.AlterField(
            model_name='emissions',
            name='lc_agb_value',
            field=models.FloatField(help_text='Emissions'),
        ),
    ]
