# Generated by Django 4.1 on 2023-08-28 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scap', '0003_alter_boundaryfiles_nomedep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boundaryfiles',
            name='nomemun',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
