# Generated by Django 4.1 on 2024-02-09 19:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('scap', '0004_emissions_total_agb_alter_emissions_lc_agb_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boundaryfiles',
            options={'verbose_name_plural': 'BoundaryFiles'},
        ),
    ]
