# Generated by Django 4.1 on 2023-08-28 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scap', '0005_boundaryfiles_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boundaryfiles',
            name='country',
        ),
    ]
