# Generated by Django 4.1 on 2023-08-28 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scap', '0006_remove_boundaryfiles_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='AOI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.IntegerField()),
            ],
        ),
    ]
