# Generated by Django 4.1 on 2023-08-28 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scap', '0007_aoi'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AOI',
        ),
    ]
