# Generated by Django 4.1 on 2023-08-28 18:30

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scap', '0008_delete_aoi'),
    ]

    operations = [
        migrations.CreateModel(
            name='AOI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wdpaid', models.FloatField()),
                ('wdpa_pid', models.CharField(max_length=52)),
                ('pa_def', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=254)),
                ('orig_name', models.CharField(max_length=254)),
                ('desig', models.CharField(max_length=254, null=True)),
                ('desig_eng', models.CharField(max_length=254, null=True)),
                ('desig_type', models.CharField(max_length=20, null=True)),
                ('iucn_cat', models.CharField(max_length=20)),
                ('int_crit', models.CharField(max_length=100)),
                ('marine', models.CharField(max_length=20)),
                ('rep_m_area', models.FloatField()),
                ('gis_m_area', models.FloatField()),
                ('rep_area', models.FloatField()),
                ('gis_area', models.FloatField()),
                ('no_take', models.CharField(max_length=50)),
                ('no_tk_area', models.FloatField()),
                ('status', models.CharField(max_length=100)),
                ('status_yr', models.IntegerField()),
                ('gov_type', models.CharField(max_length=254)),
                ('own_type', models.CharField(max_length=254)),
                ('mang_auth', models.CharField(max_length=254)),
                ('mang_plan', models.CharField(max_length=254)),
                ('verif', models.CharField(max_length=20)),
                ('metadataid', models.IntegerField()),
                ('sub_loc', models.CharField(max_length=100)),
                ('parent_iso', models.CharField(max_length=50)),
                ('iso3', models.CharField(max_length=50)),
                ('supp_info', models.CharField(max_length=254)),
                ('cons_obj', models.CharField(max_length=100, null=True)),
                ('layer', models.CharField(max_length=254)),
                ('path', models.CharField(max_length=254)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
