# Generated by Django 4.1 on 2023-08-30 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scap', '0009_aoi'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForestCoverChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(help_text='Year the change was calculated for')),
                ('baseline_year', models.IntegerField(blank=True, help_text='Baseline Year for forest cover change calculation', null=True)),
                ('initial_forest_area', models.FloatField(help_text='Initial forest area for baseline year')),
                ('forest_gain', models.FloatField(help_text='Forest Gain', null=True)),
                ('forest_loss', models.FloatField(help_text='Forest Loss')),
                ('processing_time', models.FloatField(blank=True, help_text='Time to calculate forest change data for this time period, AOI and Forest Cover Change source (seconds)', null=True)),
                ('aoi', models.ForeignKey(default=1, help_text='AOI the calculation was made for', on_delete=django.db.models.deletion.CASCADE, to='scap.predefinedaoi')),
                ('fc_source', models.ForeignKey(help_text='Forest Cover Source', on_delete=django.db.models.deletion.CASCADE, to='scap.boundaryfiles')),
            ],
        ),
    ]
