# Generated by Django 4.1 on 2023-08-30 22:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scap', '0010_forestcoverchange'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForestCoverChangeFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(help_text='Year the change was calculated for')),
                ('baseline_year', models.IntegerField(blank=True, help_text='Baseline year for forest cover change calculation', null=True)),
                ('created', models.DateTimeField(default=datetime.datetime.now, help_text='Date and time the file was created')),
                ('processing_time', models.FloatField(blank=True, help_text='Time to generate the file (seconds)', null=True)),
                ('file_name', models.CharField(default='', help_text='Forest Cover Change file name', max_length=200)),
                ('file_directory', models.CharField(default='', help_text='Forest Cover Change file directory', max_length=200)),
                ('fc_source', models.ForeignKey(help_text='Forest Cover Source', on_delete=django.db.models.deletion.CASCADE, to='scap.boundaryfiles')),
            ],
            options={
                'verbose_name_plural': 'Forest Cover Change Files',
            },
        ),
    ]
