# Generated by Django 4.1 on 2023-08-30 22:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scap', '0011_forestcoverchangefile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForestCoverFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(default='', help_text='Forest Cover Source file name', max_length=100)),
                ('file_directory', models.CharField(default='', help_text='Forest Cover Source file directory', max_length=100)),
                ('created', models.DateTimeField(default=datetime.datetime.now, help_text='Date and time the file was created')),
                ('fc_source', models.ForeignKey(help_text='Forest Cover Source', on_delete=django.db.models.deletion.CASCADE, to='scap.boundaryfiles')),
            ],
            options={
                'verbose_name_plural': 'Forest Cover Files',
            },
        ),
    ]
