# Generated by Django 4.1 on 2023-08-31 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scap', '0012_forestcoverfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forestcoverchange',
            name='aoi',
            field=models.ForeignKey(default=1, help_text='AOI the calculation was made for', on_delete=django.db.models.deletion.CASCADE, to='scap.aoi'),
        ),
    ]
