# Generated by Django 4.1 on 2023-09-06 17:25

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scap', '0013_alter_forestcoverchange_aoi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aoi',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=54009),
        ),
    ]
