# Generated by Django 4.1 on 2023-09-06 17:42

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scap', '0014_alter_aoi_geom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aoi',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(default=4326, srid=54009),
        ),
    ]
