# Generated by Django 4.1 on 2023-09-06 19:13

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scap', '0015_alter_aoi_geom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aoi',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
        ),
    ]
