from datetime import datetime
from time import timezone
from colorfield.fields import ColorField
from django.db import models

class AGBSource(models.Model):
    agb_id = models.CharField(max_length=10, primary_key=True,
                              help_text="AGB ID number")
    agb_name = models.CharField(max_length=100, default="", help_text="AGB Data Source name")

    def __str__(self):
        return self.agb_name

    def agb_label(self):
        return "AGB" + self.agb_id


class PredefinedAOI(models.Model):
    # aoi_id = models.CharField(max_length=10, primary_key=True,
    #                           help_text="AOI ID number")
    aoi_name = models.CharField(max_length=100, default="", help_text="AOI Name")
    aoi_country = models.CharField(max_length=2, help_text="AOI Country")
    aoi_geojson = models.TextField(blank=False, default="")

    def __str__(self):
        return self.aoi_name

    def aoi_label(self):
        return "AOI" + str(self.id)

# -------------------------------------------------------------------------------------------------
# ForestCoverSource model: This model stores the different sources of forest cover data
# -------------------------------------------------------------------------------------------------
class ForestCoverSource(models.Model):
    # Use autogenerated IDs (don't rely on a user defined a primary key)
    fcs_name = models.CharField(max_length=100, default="", help_text="Forest Cover Data Source Name")
    fcs_color = ColorField(default="#FF0000")
    fcs_description = models.TextField(default="", help_text="Forest Cover Data Source Description")
    fcs_metadata = models.URLField(default="https://", help_text="Forest Cover Data Source Metadata URL")
    private = models.BooleanField(default=False, help_text="Private data source?")
    # Leave the user_id field out for now, but we will add it later
    # This will be a foreign key to the user table
    # user_id = models.CharField(max_length=100, default="", help_text="User ID")

    def __str__(self):
        return self.fcs_name

    def lc_label(self):
        return "fc" + self.id


# -----------------------------------------------------------------
# Emissions model: This model stores pre-calculated emission for each predefined AOI, land cover, and AGB data source
# The objects in this model are created through an automated process to be implemented as part of S-CAP ETLs
# -----------------------------------------------------------------
class Emissions(models.Model):
    # id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False) - Let's use autogenerated IDs
    lc_id = models.ForeignKey(ForestCoverSource, default=1, verbose_name="LandCover", on_delete=models.SET_DEFAULT)
    agb_id = models.ForeignKey(AGBSource, default=1, verbose_name="AGB", on_delete=models.SET_DEFAULT)
    aoi_id = models.ForeignKey(PredefinedAOI, default=1, verbose_name="AOI", on_delete=models.SET_DEFAULT)
    year = models.IntegerField(help_text="Year")
    baseline_year = models.IntegerField(help_text="Baseline Year for emissions calculations", blank=True, null=True)
    lc_agb_value = models.FloatField(help_text="Value")


    class Meta:
        verbose_name_plural = "Emissions"

# ---------------------------------------------------------------------------------------------
# ForestCoverFile model: This model stores the locations of the forest cover files uploaded to the system
#   Eventually these files will be associated with the user who provided them
# ---------------------------------------------------------------------------------------------
class ForestCoverFile(models.Model):
    # Use autogenerated IDs (don't rely on a user defined a primary key)
    fc_source = models.ForeignKey(ForestCoverSource, help_text="Forest Cover Source", on_delete=models.CASCADE)
    file_name = models.CharField(max_length=100, default="", help_text="Forest Cover Source file name")
    file_directory = models.CharField(max_length=100, default="", help_text="Forest Cover Source file directory")
    created = models.DateTimeField(help_text='Date and time the file was created', default=datetime.now)
    # Leave the user_id field out for now, but we will add it later
    # This will be a foreign key to the user table
    # user_id = models.CharField(max_length=100, default="", help_text="User ID")

    class Meta:
        verbose_name_plural = "Forest Cover Files"

# ---------------------------------------------------------------------------------------------
# ForestCoverChangeFile model: This model stores the locations of the forest cover change files
# derived by the system. These files are created by the system as part of the ETL process.
# For estimating performance issues, we will store the time it took to generate the file and the
# date and time the file was created.
# ---------------------------------------------------------------------------------------------
class ForestCoverChangeFile(models.Model):
    # Use autogenerated IDs (don't rely on a user defined a primary key)
    fc_source = models.ForeignKey(ForestCoverSource, help_text="Forest Cover Source", on_delete=models.CASCADE)
    year = models.IntegerField(help_text="Year the change was calculated for")
    baseline_year = models.IntegerField(help_text="Baseline year for forest cover change calculation", blank=True, null=True)
    created = models.DateTimeField(help_text='Date and time the file was created', default=datetime.now)
    processing_time = models.FloatField(help_text="Time to generate the file (seconds)", blank=True, null=True)
    file_name = models.CharField(max_length=200, default="", help_text="Forest Cover Change file name")
    file_directory = models.CharField(max_length=200, default="", help_text="Forest Cover Change file directory")


    class Meta:
        verbose_name_plural = "Forest Cover Change Files"

# -----------------------------------------------------------------
# LandCoverChange model: This model stores pre-calculated land cover change data for each predefined AOI (forest gain
# and loss, plus initial forest area for the baseline year)
# Note: Standard units for area measurements pending (hectares, km2, etc.)
# The objects in this model are created through an automated process to be implemented as part of S-CAP ETLs
# -----------------------------------------------------------------
class ForestCoverChange(models.Model):
    fc_source = models.ForeignKey(ForestCoverSource, help_text="Forest Cover Source", on_delete=models.CASCADE)
    aoi = models.ForeignKey(PredefinedAOI, default=1, help_text="AOI the calculation was made for", on_delete=models.CASCADE)
    year = models.IntegerField(help_text="Year the change was calculated for")
    baseline_year = models.IntegerField(help_text="Baseline Year for forest cover change calculation", blank=True, null=True)
    initial_forest_area = models.FloatField(help_text="Initial forest area for baseline year")
    forest_gain = models.FloatField(help_text="Forest Gain", null=True)
    forest_loss = models.FloatField(help_text="Forest Loss")
    processing_time = models.FloatField(help_text="Time to calculate forest change data for this time period, AOI and Forest Cover Change source (seconds)", blank=True, null=True)

    def net_forest_change(self):
        return self.forest_gain - self.forest_loss