import uuid

from django.db import models


class LC(models.Model):
    lc_id = models.CharField(max_length=10, primary_key=True,
                             help_text="LC ID number")
    lc_name = models.CharField(max_length=100, default="", help_text="LC Data Source name")

    def __str__(self):
        return self.lc_name
    def lc_label(self):
        return "LC" + self.lc_id


class AGB(models.Model):
    agb_id = models.CharField(max_length=10, primary_key=True,
                              help_text="AGB ID number")
    agb_name = models.CharField(max_length=100, default="", help_text="AGB Data Source name")

    def __str__(self):
        return self.agb_name
    def agb_label(self):
        return "AGB" + self.agb_id


class Predefined_AOI(models.Model):
    aoi_id = models.CharField(max_length=10, primary_key=True,
                              help_text="AOI ID number")
    aoi_name = models.CharField(max_length=100, default="", help_text="AOI Name")
    aoi_country = models.CharField(max_length=2, help_text="AOI Country")

    def __str__(self):
        return self.aoi_name
    def aoi_label(self):
        return "AOI" + self.aoi_id

# -----------------------------------------------------------------
# Emissions model: This model stores pre-calculated emission for each predefined AOI, land cover, and AGB data source
# The objects in this model are created through an automated process to be implemented as part of S-CAP ETLs
# -----------------------------------------------------------------
class Emissions(models.Model):
    # id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False) - Let's use autogenerated IDs
    lc_id = models.ForeignKey(LC, default=1, verbose_name="LandCover", on_delete=models.SET_DEFAULT)
    agb_id = models.ForeignKey(AGB, default=1, verbose_name="AGB", on_delete=models.SET_DEFAULT)
    aoi_id = models.ForeignKey(Predefined_AOI, default=1, verbose_name="AOI", on_delete=models.SET_DEFAULT)
    year = models.IntegerField(help_text="Year")
    baseline_year = models.IntegerField(help_text="Baseline Year for emissions calculations", blank=True, null=True)
    lc_agb_value = models.FloatField(help_text="Value")

# -----------------------------------------------------------------
# LandCoverChange model: This model stores pre-calculated land cover change data for each predefined AOI (forest gain 
# and loss, plus initial forest area for the baseline year)
# Note: Standard units for area measurements pending (hectares, km2, etc.)
# The objects in this model are created through an automated process to be implemented as part of S-CAP ETLs
# -----------------------------------------------------------------
class ForestCoverChange(models.Model):
    lc_id = models.ForeignKey(LC, default=1, verbose_name="LandCover", on_delete=models.SET_DEFAULT)
    aoi_id = models.ForeignKey(Predefined_AOI, default=1, verbose_name="AOI", on_delete=models.CASCADE)
    year = models.IntegerField(help_text="Year")
    baseline_year = models.IntegerField(help_text="Baseline Year for forest cover calculations", blank=True, null=True)
    initial_forest_area = models.FloatField(help_text="Initial forest area for baseline year")
    forest_gain = models.FloatField(help_text="Forest Gain", null=True)
    forest_loss = models.FloatField(help_text="Forest Loss")

    def net_forest_change(self):
        return self.forest_gain - self.forest_loss
    
