# Generated by Django 4.1 on 2023-06-13 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AGB',
            fields=[
                ('agb_id',
                 models.CharField(help_text='AGB ID number', max_length=10, primary_key=True, serialize=False)),
                ('agb_name', models.CharField(default='', help_text='AGB Data Source name', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LC',
            fields=[
                ('lc_id', models.CharField(help_text='LC ID number', max_length=10, primary_key=True, serialize=False)),
                ('lc_name', models.CharField(default='', help_text='LC Data Source name', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Predefined_AOI',
            fields=[
                ('aoi_id',
                 models.CharField(help_text='AOI ID number', max_length=10, primary_key=True, serialize=False)),
                ('aoi_name', models.CharField(default='', help_text='AOI Name', max_length=100)),
                ('aoi_country', models.CharField(help_text='AOI Country', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='ForestCoverChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(help_text='Year')),
                ('baseline_year',
                 models.IntegerField(blank=True, help_text='Baseline Year for forest cover calculations', null=True)),
                ('initial_forest_area', models.FloatField(help_text='Initial forest area for baseline year')),
                ('forest_gain', models.FloatField(help_text='Forest Gain')),
                ('forest_loss', models.FloatField(help_text='Forest Loss')),
                ('aoi_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,
                                             to='scapadmin.predefined_aoi', verbose_name='AOI')),
                ('lc_id',
                 models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='scapadmin.lc',
                                   verbose_name='LandCover')),
            ],
        ),
        migrations.CreateModel(
            name='Emissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(help_text='Year')),
                ('baseline_year',
                 models.IntegerField(blank=True, help_text='Baseline Year for emissions calculations', null=True)),
                ('lc_agb_value', models.FloatField(help_text='Value')),
                ('agb_id',
                 models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='scapadmin.agb',
                                   verbose_name='AGB')),
                ('aoi_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,
                                             to='scapadmin.predefined_aoi', verbose_name='AOI')),
                ('lc_id',
                 models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='scapadmin.lc',
                                   verbose_name='LandCover')),
            ],
        ),
    ]
