# Generated by Django 4.1 on 2023-07-25 20:14

import colorfield.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AGBSource',
            fields=[
                ('agb_id', models.CharField(help_text='AGB ID number', max_length=10, primary_key=True, serialize=False)),
                ('agb_name', models.CharField(default='', help_text='AGB Data Source name', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ForestCoverSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fcs_name', models.CharField(default='', help_text='Forest Cover Data Source Name', max_length=100)),
                ('fcs_color', colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=18, samples=None)),
                ('fcs_description', models.TextField(default='', help_text='Forest Cover Data Source Description')),
                ('fcs_metadata', models.URLField(default='https://', help_text='Forest Cover Data Source Metadata URL')),
                ('private', models.BooleanField(default=False, help_text='Private data source?')),
            ],
        ),
        migrations.CreateModel(
            name='PredefinedAOI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aoi_name', models.CharField(default='', help_text='AOI Name', max_length=100)),
                ('aoi_country', models.CharField(help_text='AOI Country', max_length=2)),
                ('aoi_geojson', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='ForestCoverFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(default='', help_text='Forest Cover Source file name', max_length=100)),
                ('file_directory', models.CharField(default='', help_text='Forest Cover Source file directory', max_length=100)),
                ('created', models.DateTimeField(default=datetime.datetime.now, help_text='Date and time the file was created')),
                ('fc_source', models.ForeignKey(help_text='Forest Cover Source', on_delete=django.db.models.deletion.CASCADE, to='scapadmin.forestcoversource')),
            ],
            options={
                'verbose_name_plural': 'Forest Cover Files',
            },
        ),
        migrations.CreateModel(
            name='ForestCoverChangeFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(help_text='Year the change was calculated for')),
                ('baseline_year', models.IntegerField(blank=True, help_text='Baseline year for forest cover change calculation', null=True)),
                ('created', models.DateTimeField(default=datetime.datetime.now, help_text='Date and time the file was created')),
                ('processing_time', models.FloatField(blank=True, help_text='Time to generate the file (seconds)', null=True)),
                ('file_name', models.CharField(default='', help_text='Forest Cover Change file name', max_length=200)),
                ('file_directory', models.CharField(default='', help_text='Forest Cover Change file directory', max_length=200)),
                ('fc_source', models.ForeignKey(help_text='Forest Cover Source', on_delete=django.db.models.deletion.CASCADE, to='scapadmin.forestcoversource')),
            ],
            options={
                'verbose_name_plural': 'Forest Cover Change Files',
            },
        ),
    ]
