# Generated by Django 4.1 on 2023-06-05 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scapadmin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='predefined_aoi',
            old_name='aoi_year',
            new_name='aoi_country',
        ),
        migrations.AddField(
            model_name='predefined_aoi',
            name='aoi_name',
            field=models.CharField(default='', help_text='AOI Year', max_length=100),
        ),
    ]
