# Generated by Django 4.1 on 2023-06-13 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('scapadmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emissions',
            name='aoi_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT,
                                    to='scapadmin.predefined_aoi', verbose_name='AOI'),
        ),
    ]
