# Generated by Django 4.1 on 2023-07-25 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scapadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForestCoverChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(help_text='Year the change was calculated for')),
                ('baseline_year', models.IntegerField(blank=True, help_text='Baseline Year for forest cover change calculation', null=True)),
                ('initial_forest_area', models.FloatField(help_text='Initial forest area for baseline year')),
                ('forest_gain', models.FloatField(help_text='Forest Gain', null=True)),
                ('forest_loss', models.FloatField(help_text='Forest Loss')),
                ('processing_time', models.FloatField(blank=True, help_text='Time to calculate forest change data for this time period, AOI and Forest Cover Change source (seconds)', null=True)),
                ('aoi', models.ForeignKey(default=1, help_text='AOI the calculation was made for', on_delete=django.db.models.deletion.CASCADE, to='scapadmin.predefinedaoi')),
                ('fc_source', models.ForeignKey(help_text='Forest Cover Source', on_delete=django.db.models.deletion.CASCADE, to='scapadmin.forestcoversource')),
            ],
        ),
        migrations.CreateModel(
            name='Emissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(help_text='Year')),
                ('baseline_year', models.IntegerField(blank=True, help_text='Baseline Year for emissions calculations', null=True)),
                ('lc_agb_value', models.FloatField(help_text='Value')),
                ('agb_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='scapadmin.agbsource', verbose_name='AGB')),
                ('aoi_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='scapadmin.predefinedaoi', verbose_name='AOI')),
                ('lc_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='scapadmin.forestcoversource', verbose_name='LandCover')),
            ],
            options={
                'verbose_name_plural': 'Emissions',
            },
        ),
    ]
