# Generated by Django 4.1 on 2023-06-20 17:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('scapadmin', '0002_alter_emissions_aoi_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forestcoverchange',
            name='forest_gain',
            field=models.FloatField(help_text='Forest Gain', null=True),
        ),
    ]
