# Generated by Django 4.1 on 2023-06-05 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scapadmin', '0002_rename_aoi_year_predefined_aoi_aoi_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agb',
            name='lc_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='scapadmin.lc', verbose_name='LandCover'),
        ),
    ]
