# Generated by Django 4.1 on 2023-06-28 20:54

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('scapadmin', '0003_alter_forestcoverchange_forest_gain'),
    ]

    operations = [
        migrations.AddField(
            model_name='lc',
            name='lc_color',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=18, samples=None),
        ),
    ]
