# Generated by Django 4.1 on 2023-06-05 14:13

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('scapadmin', '0003_agb_lc_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='agb',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='agb',
            name='agb_id',
            field=models.CharField(help_text='AGB ID number', max_length=10),
        ),
    ]
