# Generated by Django 4.1 on 2023-06-05 14:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('scapadmin', '0004_agb_id_alter_agb_agb_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lc',
            name='lc_value',
        ),
        migrations.RemoveField(
            model_name='lc',
            name='lc_year',
        ),
        migrations.AlterField(
            model_name='lc',
            name='lc_id',
            field=models.CharField(help_text='LC ID number', max_length=10, primary_key=True, serialize=False),
        ),
    ]
