# Generated by Django 4.1 on 2023-06-05 14:18

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('scapadmin', '0005_remove_lc_lc_value_remove_lc_lc_year_alter_lc_lc_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agb',
            name='agb_value',
        ),
        migrations.RemoveField(
            model_name='agb',
            name='agb_year',
        ),
        migrations.RemoveField(
            model_name='agb',
            name='id',
        ),
        migrations.RemoveField(
            model_name='agb',
            name='lc_id',
        ),
        migrations.RemoveField(
            model_name='predefined_aoi',
            name='aoi_value',
        ),
        migrations.AlterField(
            model_name='agb',
            name='agb_id',
            field=models.CharField(help_text='AGB ID number', max_length=10, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agb_year', models.IntegerField(help_text='Year')),
                ('lc_agb_value', models.FloatField(help_text='Value')),
                ('agb_id',
                 models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='scapadmin.agb',
                                   verbose_name='AGB')),
                ('lc_id',
                 models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='scapadmin.lc',
                                   verbose_name='LandCover')),
            ],
        ),
    ]
