# Generated by Django 4.1 on 2023-06-05 14:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('scapadmin', '0006_remove_agb_agb_value_remove_agb_agb_year_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='value',
            old_name='agb_year',
            new_name='year',
        ),
    ]
