# Generated by Django 4.2.1 on 2023-06-09 15:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('scapadmin', '0007_rename_agb_year_value_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='agb',
            name='agb_name',
            field=models.CharField(default='', help_text='AGB Data Source name', max_length=100),
        ),
        migrations.AddField(
            model_name='lc',
            name='lc_name',
            field=models.CharField(default='', help_text='LC Data Source name', max_length=100),
        ),
    ]
