# Generated by Django 4.1 on 2023-06-09 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scapadmin', '0008_agb_agb_name_lc_lc_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Value',
            new_name='Emissions',
        ),
    ]
